version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.44
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6217:4317"
      - "6286:16686"

networks:
  default:
